import type { Metadata } from "next";
import "./cms.css"
import "../../(app)/globals.css"
import DashboardSidenav from "./components/sidenav";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function CmsLayout({
    children,
}:Readonly<{
    children:React.ReactNode
}>){
    return (
        <html lang="en">
            <body>
                <div className="grid grid-cols-[auto_1fr] w-full h-screen">
                <DashboardSidenav />
                {children}
            </div>
            </body>
        </html>
    )
}